version: "3.0"

services:

  db_healthpilot:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5433:5432"
    networks:
      - health-net
    volumes:
      - ./healthpilotdata/db:/var/lib/postgresql/healthpilotdata
    env_file:
      - ".env_file"

  healthpilot:
    build: .
    restart: always
    volumes:
      - .:/healthpilot
      - dem:/etc/systemd/system:rw
      - static:/static
    command: >
      bash -c "python manage.py migrate --no-input && \
               python manage.py collectstatic  --no-input && \
               daphne -b 0.0.0.0 -p 8000 healthpilot.asgi:application"

    ports:
    - "8001:80"

    networks:
      - health-net
    depends_on:
      - db_healthpilot

  nginx_healthpilot:
    build: ./nginx
    volumes:
      - static:/static
    networks:
      - health-net
    ports:
      - "8002:80"

    depends_on:
      - healthpilot

  rabbitmq_healthpilot:
    image: rabbitmq:3.9.10-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: on-failure
    env_file:
      - ".env_file"
    networks:
      - health-net

  celery_healthpilot:
    build: .
    restart: always
    command: celery -A healthpilot worker -l info --uid=nobody --gid=nogroup
    volumes:
      - ./celerydata/celery/:/usr/src/app/
    env_file:
      - ".env_file"
    networks:
      - health-net
    depends_on:
      - db_healthpilot
      - rabbitmq_healthpilot


  celery-beat_healthpilot:
    build: .
    restart: always
    volumes:
      - ./celerydata/beat/:/usr/src/app/
    command: celery -A healthpilot beat -l info
    networks:
      - health-net
    env_file:
      - ".env_file"
    depends_on:
       - celery_healthpilot
       - rabbitmq_healthpilot
       - db_healthpilot
       - healthpilot

  # newly added server
  daphne_healthpilot:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 healthpilot.asgi:application
    expose:
      - 8000
    depends_on:
      - db_healthpilot
    volumes:
      - static:/static
    networks:
      - health-net
      
volumes:
  static:
  dem: null

networks:
  health-net:
    driver: bridge