# Generated by Django 4.2.1 on 2023-05-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="created_at", new_name="joined_at",
        ),
    ]
